version: '3'

services:

  omero-db:
    image: postgres:9.6.12-alpine
    networks:
      ome_seadragon_env:
        aliases:
          - ome-pg-server
    environment:
      - POSTGRES_DB=omero
      - POSTGRES_USER=omero
      - POSTGRES_PASSWORD=omero
    volumes:
      - ome-pg-data:/var/lib/postgresql/data

  redis-server:
    image: redis:6.0.3-alpine
    command: ["redis-server", "--appendonly", "yes"]
    networks:
      ome_seadragon_env:
        aliases:
          - redis-server
    volumes:
      - redis-data:/data

  omero-server:
    image: openmicroscopy/omero-server:5.6.1
    depends_on:
      - omero-db
    networks:
      ome_seadragon_env:
        aliases:
          - omero-server
    ports:
      - "4063:4063"
      - "4064:4064"
    environment:
      - ROOTPASS=omero
      - CONFIG_omero_db_host=ome-pg-server
      - CONFIG_omero_db_user=omero
      - CONFIG_omero_db_pass=omero
      - CONFIG_omero_db_name=omero
    volumes:
      - ome-data-dir:/OMERO
      - ome-server-var:/opt/omero/server/OMERO.server/var

  ome_seadragon-web:
    image: crs4/ome_seadragon-web:0.7.0-ome5.6.3
    depends_on:
      - omero-server
      - redis-server
    entrypoint: ['/usr/local/bin/wait-for-it.sh', 'redis-server:6379', '--',
                 '/usr/local/bin/wait-for-it.sh', 'omero-server:4063', '--timeout=600', '--strict', '--',
                 '/usr/local/bin/wait-for-it.sh', 'omero-server:4064', '--timeout=600', '--strict', '--',
                 '/usr/local/bin/entrypoint.sh']
    networks:
      ome_seadragon_env:
        aliases:
          - ome_seadragon-web
    environment:
      - ROOTPASS=omero
      - OMEROHOST=omero-server
      - REDISHOST=redis-server
      - IMAGES_REPOSITORY=/OMERO/
      - GW_USER_NAME=ome_gw
      - GW_USER_PASS=omero
    volumes:
      - ome-data-dir:/OMERO

  ome_seadragon-nginx:
    image: crs4/ome_seadragon-nginx:0.7.0-ome5.6.3
    depends_on:
      - ome_seadragon-web
      - nginx-proxy
    entrypoint: ['/usr/local/bin/wait-for-it.sh', 'ome_seadragon-web:4080', '--timeout=600', '--strict', '--',
                 '/usr/local/bin/entrypoint.sh']
    networks:
      ome_seadragon_env:
        aliases:
          - ome_seadragon-nginx
          - ome-seadragon.local
    environment:
      - OMEROWEBHOST=ome_seadragon-web
      - VIRTUAL_HOST=ome-seadragon.local

  ome_seadragon_gw-db:
    image: postgres:9.6.12-alpine
    networks:
      ome_seadragon_env:
        aliases:
          - ome_seadragon_gw-db
    environment:
      - POSTGRES_DB=ome_seadragon_gw
      - POSTGRES_USER=ome_seadragon
      - POSTGRES_PASSWORD=omero
    volumes:
      - ome-seadragon-gw-pg-data:/var/lib/postgresql/data

  ome_seadragon_gw-web:
    image: crs4/ome_seadragon_gw-web:0.1.3
    depends_on:
      - ome_seadragon-nginx
      - redis-server
      - ome_seadragon_gw-db
    entrypoint: ['/usr/local/bin/wait-for-it.sh', 'redis-server:6379', '--',
                 '/usr/local/bin/wait-for-it.sh', 'ome_seadragon_gw-db:5432', '--',
                 '/usr/local/bin/wait-for-it.sh', 'ome_seadragon-nginx:80', '--timeout=600', '--strict','--',
                 '/usr/local/bin/entrypoint.sh']
    networks:
      ome_seadragon_env:
        aliases:
          - ome_seadragon_gw-web
    environment:
      - DJANGO_CONFIG_FILE=/opt/django/conf/config.yaml
    volumes:
      - ./ome_seadragon_gw_config/:/opt/django/conf/

  ome_seadragon_gw-nginx:
    image: crs4/ome_seadragon_gw-nginx:0.1.3
    depends_on:
      - ome_seadragon_gw-web
      - nginx-proxy
    entrypoint: ['/usr/local/bin/wait-for-it.sh', 'ome_seadragon_gw-web:8080', '--timeout=600', '--strict', '--',
                 '/usr/local/bin/entrypoint.sh']
    networks:
      ome_seadragon_env:
        aliases:
          - ome_seadragon_gw-nginx
          - ome-seadragon-gw.local
    environment:
      - DJANGO_SERVER=ome_seadragon_gw-web
      - VIRTUAL_HOST=ome-seadragon-gw.local

  nginx-proxy:
    image: jwilder/nginx-proxy
    networks:
      ome_seadragon_env:
        aliases:
          - nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

volumes:
  ome-pg-data: null
  ome-seadragon-gw-pg-data: null
  ome-server-var: null
  ome-data-dir: null
  redis-data: null

networks:
  ome_seadragon_env: null
